#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N OpenCLWrapper

# Name of stdout output file
#PBS -o job.out

# Total number of nodes and MPI tasks/node requested
#PBS -l nodes=compute-1-0

# Run time (hh:mm:ss) - 1.5 hours
#PBS -l walltime=01:30:00
#----------------------------------------------------------

# Change to submission directory
cd $PBS_O_WORKDIR

cat $PBS_NODEFILE
sort $PBS_NODEFILE | uniq > machines2
cat machines2
export LD_LIBRARY_PATH=/share/apps/AMDAPPSDK-3.0/lib/x86_64/:$LD_LIBRARY_PATH
# Launch MPI-based executable
/opt/ohpc/pub/mpi/mpich-ofi-gnu13-ohpc/3.4.3/bin/mpirun -np 1 -machinefile machines2 ./a.out
